[managers]
# it should be the docker container name of the manager node, in our case "manager" prefixed by docker compose
ansible-manager-1

[managers:vars]
ansible_connection=community.docker.docker

[workers]
# it should be the docker container name of the worker nodes, in our case "node" prefixed by docker compose
ansible-node-1
ansible-node-2
ansible-node-3
ansible-node-4

[workers:vars]
ansible_connection=community.docker.docker