name: Build - client
run-name: "${{ github.run_id }}: Build client image for commit ${{ github.ref_name }}"
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v5
        - name: Build the client image
          run: docker build -t client-image:${{ github.sha }} ./client
