name: CI - server
run-name: "${{ github.run_id }}: Run server tests for commit ${{ github.ref }}"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (server)
        run: npm install
        working-directory: ./server

      - name: Run tests (server)
        run: npm test
        working-directory: ./server

